[[Wine]]
arch = "x86_64"
git-tree-sha1 = "dcecd51dec4de4aebeef84b506c0eb87b5df026a"
os = "macos"

    [[Wine.download]]
    sha256 = "f9423d9317452206ca9792ef0d11fb62a7ac8a9fe1b7e339a560006f2de0ddf6"
    url = "https://github.com/JuliaBinaryWrappers/Wine_jll.jl/releases/download/Wine-v7.0.0-rc3+1/Wine.v7.0.0-rc3.x86_64-apple-darwin.tar.gz"
[[Wine]]
arch = "x86_64"
git-tree-sha1 = "c460a506e0bb5dd8f1467d21c273568349469c16"
libc = "glibc"
os = "linux"

    [[Wine.download]]
    sha256 = "0cb35dee1ca45ea05468f4c2ef08e0929d7f0f7ad44d7d4eac468aad7fa82047"
    url = "https://github.com/JuliaBinaryWrappers/Wine_jll.jl/releases/download/Wine-v7.0.0-rc3+1/Wine.v7.0.0-rc3.x86_64-linux-gnu.tar.gz"
[[Wine]]
arch = "x86_64"
git-tree-sha1 = "792d957af6d17996e49d4ebd5d8a8fcece7a0422"
libc = "musl"
os = "linux"

    [[Wine.download]]
    sha256 = "7eb47fda14ad238d20b4832292cf778177f9a422a512377394930d980ffe9c0d"
    url = "https://github.com/JuliaBinaryWrappers/Wine_jll.jl/releases/download/Wine-v7.0.0-rc3+1/Wine.v7.0.0-rc3.x86_64-linux-musl.tar.gz"
